### ISSUE TITLE
Decoded PSET balance bug

### ISSUE THREAD

**Issue by Saleciani** [SatoshiPortal/lwk-dart#22]
If the receive address is the a self deposit address (generated from the same wallet as sending), decoding a PSET with maximum value will generate a balance of -1.

Not sure if the pset generated is incorrect, or the decoded pset itself.
--PSET enhancements ideas--
build_lbtc_tx takes a absFee param wich i assume is sats/vb

But on the decoded pset it returns an absolute value correct?
Enchancement idea could be a naming change to have these more clear

Would be cool to have a drain wallet method, this way i wont have to loop over amount to send until i find a sending amount where lwk builds a transaction without sending an error to find the max.

**Comment by i5hi** [comment]
We confirmed that build_lbtc_tx takes fee_rate of `sats/kvb`

Renaming PsetBalances.fees to .absolute_fees sounds good. I will make this change.

Drain would be nice! Something we need from lwk. Or else, we could write that (looping) logic ourselves in rust so that dart clients dont have to - until lwk supports it.

**Comment by Saleciani** [comment]
Issue solved
